name: 'AkonOldPvP'
main: com.akon.oldpvp.OldPvP
version: 1.3
author: akon
depend: [ProtocolLib]

commands:
  oldpvp:
    permission: oldpvp.command.reload
    usage: /oldpvp reload

permissions:
  oldpvp.command.reload:
    default: op